spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #active: native
  cloud:
    config:
      server:
        #native:
          #search-locations: "file:///Users/users/Desktop/config/"
        #search-locations: "classpath:/config"
        git:
          uri: "https://github.com/warrior226/EazyBankApp-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
      host: "localhost"
      port: 5672
      username: "guest"
      password: "guest"
encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"


server:
  port: 8071


#for actuator (enable cards microservice to load changed properties from the config server without restart)
management:
  endpoints:
    web:
      exposure:
        include: "*"